name: Build Universal APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Android SDK
        uses: android-actions/setup-android@v3
        with:
          ndk-version: '21.4.7075529'
          cmake-version: '3.18.1'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install -g cordova@latest
          npm ci
          cordova platform add android@latest

      - name: Build APK
        run: |
          cordova build android --release -- --packageType=apk
          mv platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk blackjack-universal.apk

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: blackjack-wearos.apk
          path: blackjack-universal.apk
